#!/usr/bin/env php
<?php

require 'bootstrap.php';

$config = require APP_PATH . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);